defaults:
  - _self_
  - trainer: test
  - model: maxvit_aggregated
  - loss: mae_aggregated
  - metric: metric
  - accelerate: gpu_amp
  - dataset: [test/test]
  - loader: b16_w4
  - collate_fn:
  - transform: transform
  - callbacks: test
  - hydra: default
